// <auto-generated />
using System;
using EPG_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPG_Api.Migrations
{
    [DbContext(typeof(EPGContext))]
    [Migration("20220531081511_EPG")]
    partial class EPG
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPG_Api.Models.EpgTva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short?>("CdNibble1")
                        .HasColumnType("smallint")
                        .HasColumnName("cd_nibble1");

                    b.Property<short?>("CdNibble2")
                        .HasColumnType("smallint")
                        .HasColumnName("cd_nibble2");

                    b.Property<string>("Channel")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("channel");

                    b.Property<DateTime?>("DateProd")
                        .HasColumnType("date")
                        .HasColumnName("date_prod");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("duration");

                    b.Property<string>("EedLangAlb")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("eed_lang_alb");

                    b.Property<string>("EedLangEng")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("eed_lang_eng");

                    b.Property<string>("EedTextAlb")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("eed_text_alb");

                    b.Property<string>("EedTextEng")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("eed_text_eng");

                    b.Property<int?>("Eid")
                        .HasColumnType("int")
                        .HasColumnName("eid");

                    b.Property<byte[]>("Genre")
                        .HasMaxLength(250)
                        .HasColumnType("varbinary(250)")
                        .HasColumnName("genre");

                    b.Property<string>("Poster")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("poster");

                    b.Property<string>("PrdCountryCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prd_country_code");

                    b.Property<short?>("PrdValue")
                        .HasColumnType("smallint")
                        .HasColumnName("prd_value");

                    b.Property<string>("SedLangAlb")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sed_lang_alb");

                    b.Property<string>("SedLangEng")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("sed_lang_eng");

                    b.Property<string>("SedNameAlb")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("sed_name_alb");

                    b.Property<string>("SedNameEng")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("sed_name_eng");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Trailer")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("trailer");

                    b.HasKey("Id");

                    b.ToTable("EPG_TVA");
                });
#pragma warning restore 612, 618
        }
    }
}
